title:            Yu's Blog
description:      Every time you talk to them, They gotta new things done.
# disqus_shortname: shortname
# Your site's domain goes here (eg: //mmistakes.github.io, http://mademistakes.com, etc)
# When testing locally leave blank or use http://localhost:4000
url:              //uynil.github.io

# Owner/author information
owner:
  name:           LIN Yu
  avatar:         avatar.png
  bio:            "Developer. Entreprise Software"
  email:          uynill@163.com
  # Social networking links used in footer. Update and remove as you like.
  # twitter:        
  # facebook:       
  # github:         
  # stackexchange:  
  # linkedin:       
  instagram: uynil
  # flickr:         
  # tumblr:         
  # google plus id, include the '+', eg +mmistakes
  # google_plus:    +yourid

# Analytics and webmaster tools stuff goes here
# google_analytics:   
# google_verify:      
# # https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
# bing_verify:         

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Asia/Shanghai
future:      true
pygments:    true
markdown:    kramdown

# Amount of posts to show on home page
paginate: 10